version: '2'

services:
  mysql:
    build:
      context: mariadb/
    container_name: trans_trip_mysql
    volumes:
      - mysqldata:/var/lib/mysql
      - mysqllog:/var/log/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb/my.cnf:/etc/mysql/my.cnf:ro
      -  /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    networks:
      - net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sea-robber
    restart: always
  
  sea-robber-api:
    build:
      context: sea-robber-api/src/sea-robber-api/
    container_name: sea-robber-api
    volumes:
      - ./sea-robber-api/src/sea-robber-api/sea-robber-api:/app/sea-robber-api
      - ./sea-robber-api/src/sea-robber-api/app/config/config.yml.prod:/app/app/config/config.yml:ro
      - /usr/local/go/lib/time/zoneinfo.zip:/usr/local/go/lib/time/zoneinfo.zip:ro
    ports:
      - "8015:8000"
    networks:
      - net
    restart: always
    depends_on:
      - mysql


volumes:
  mysqldata:
    driver: local
  mysqllog:
    driver: local
  

networks:
  net:
    driver: bridge
